set("HUNTER_INSTALL_LICENSE_FILES" "googletest/LICENSE" CACHE INTERNAL "")
set("BUILD_GMOCK" "OFF" CACHE INTERNAL "")
set("gtest_force_shared_crt" "ON" CACHE INTERNAL "")
set("CMAKE_CXX_FLAGS" "   -DGTEST_HAS_TR1_TUPLE=0" CACHE INTERNAL "")
