set("BUILD_SHARED" "OFF" CACHE INTERNAL "")
set("BUILD_TESTING" "OFF" CACHE INTERNAL "")
set("USE_INTERMEDIATE_OBJECTS_TARGET" "OFF" CACHE INTERNAL "")
set("CMAKE_SYSTEM_VERSION" "NO" CACHE INTERNAL "")
